// URLS FOR API
export const GET_ALL_CITIZEN_SHORT_INFO = 'all/citizen'
export const GET_CITIZEN_DETAIL_INFO = 'citizen/detail'

// THRESHOLD FOR CHECKING THE AGE LIMIT, USED IN TRANSFORM CITIZEN DETAIL DATA (DUMMY FUNCTION FOR DEMO PURPOSE ONLY)
export const MAXIMUM_ALLOWED_AGE = 16